copyright = 2024
disableKinds = ["RSS", "taxonomy", "term"]
enableEmoji = true
enableRobotsTXT = true
languageCode = "en-us"
paginate = 20
pluralizeListTitles = true
relativeURLs = true
timeZone = "America/New_York"

[build]
  noJSConfigInAssets = true

  [build.buildStats]
    enable = true

[imaging]
  quality = 85

  [imaging.exif]
    disableDate = true
    disableLatLong = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.126.0"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[params]
  logo = "logo-vertical.svg"
  slogan = "Pasture-raised eggs"

  [params.defaults]
    [params.defaults.ctas]
      [params.defaults.ctas.default]
        path = "simple.html"

      [params.defaults.ctas.simple]
        text = "Place an order!"
        label = "Contact"
        link = "/contact"

    [params.defaults.featuredImage]
      [params.defaults.featuredImage.default]
        path = "default-featured-image.png"

      [params.defaults.featuredImage.linkToOriginal]
        list = true
        section = true
        single = true

[sitemap]
  changefreq = "weekly"
